name: Pylint

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: python --version
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m install --upgrade pip
          pip install pylint
          pip install flask 
          pip install requirements.txt
      - name: Analyzing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
